name: download_videos
description: "YouTube downloader & media processor built with Flutter."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  # Core UI
  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.0
  percent_indicator: ^4.2.5

  # State management
  flutter_riverpod: ^3.2.0

  # YouTube download / processing
  youtube_explode_dart: ^3.0.5

  # File system / storage
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  gal: ^2.3.2
  open_file: ^3.5.11

  # Utilities
  intl: ^0.20.2
  ffmpeg_kit_flutter_new: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

